version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "System.*"
      - dependency-name: "Microsoft.Win32.Registry.AccessControl"
      - dependency-name: "Microsoft.Windows.Compatibility"
