name: Publish Documentation

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/mkdocs/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Deploy MkDocs
        run: |
          pip install -r requirements.txt
          mkdocs gh-deploy --force
